# https://taskfile.dev

version: "3"

tasks:
  test:
    aliases: [t]
    cmds:
      - docker compose exec vm make test

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down
